name: Algolia DocSearch

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1"

jobs:
  docsearch_andexdb:
    runs-on: ubuntu-latest
    name: Algolia DocSearch (andexdb)
    steps:
      - uses: actions/checkout@v2
      - uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_api_key: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
          algolia_application_id: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          # needs to be inside $GITHUB_WORKSPACE from actions/checkout step
          file: "docs/andexdb/.vitepress/algolia/config.json"
  docsearch_main:
    runs-on: ubuntu-latest
    name: Algolia DocSearch (main)
    steps:
      - uses: actions/checkout@v2
      - uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_api_key: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
          algolia_application_id: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          # needs to be inside $GITHUB_WORKSPACE from actions/checkout step
          file: "docs/main/.vitepress/algolia/config.json"
