name: Generate Sitemap
on:
  push:
    branches:
      - generated
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:

jobs:
  generate_sitemap:
    runs-on: ubuntu-latest
    name: Generate
    env:
      GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version-file: .nvmrc
      - name: Install Sitemap Generator 🔧
        run: npm install -S sitemap-generator
      - name: Generate 🔧
        run: npm run generate-sitemap
